version: '3'
services:
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice_ds
    environment:
      - JWT_ENABLED=false  
      - JWT_SECRET=secret  
      - DS_FORCESAVE=true
      - ALLOW_PRIVATE_IP_ADDRESS=true
      - ALLOW_META_IP_ADDRESS=true
    ports:
      - "8082:80"         
    volumes:
      - ./logs:/var/log/onlyoffice
      - ./data:/var/www/onlyoffice/Data
      - ./lib:/var/lib/onlyoffice
    restart: always